import components.currentcomparison
import components.currentpace
import components.detailedtimer
import components.possibletimesave
import components.previoussegment
import components.sumofbest
import components.title
